### ISSUE TITLE
Color of the routes

### ISSUE THREAD

**Issue by sebsebien** [judero01col/GMap.NET#105]
Hello,

I am adding multiple routes with different colors to an overlay but all the routes are displayed in the same color (the color of the last route that was added).

I've also tried to work with multiple overlays (one overlay for each route) but it gives exactly the same issue: all the overlay routes are displayed in the same color.

Could you please make sure that each route that is being added is displayed in its own color: 

_route1. Stroke.Color = Color.Black;
_route2 Stroke.Color = Color.Blue;

Many thanks in advance for your help,

Seb

**Comment by jhofran** [comment]
GMapRoute routes;
Random rnd = new Random();

routes = new GMapRoute(direction.Route, "routes " + Guid.NewGuid().ToString());
routes.Stroke = new Pen(Color.FromArgb(144, Color.FromArgb(rnd.Next(256), rnd.Next(256), rnd.Next(256))));
routes.Stroke.Width = 4;
routes.Stroke.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;

RoutesOverlay.Routes.Add(routes);

routes = new GMapRoute(direction.Route, "routes " + Guid.NewGuid().ToString());
routes.Stroke = new Pen(Color.FromArgb(144, Color.FromArgb(rnd.Next(256), rnd.Next(256), rnd.Next(256))));
routes.Stroke.Width = 4;
routes.Stroke.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;

RoutesOverlay.Routes.Add(routes);

**Comment by sebsebien** [comment]
![Capture](https://user-images.githubusercontent.com/18150507/93427752-a2619400-f8be-11ea-8089-c1427dc05e62.PNG)

using GMap.NET.WindowsForms;
using GMap.NET.WindowsForms.Markers;

GMapRoute[] _route = new GMapRoute[10];

                foreach (int p in _plist)
                {
                    List<COORDS> _list = ASTRON.getGreatCircles(TH1.P, _sweph, p, 0.25);
                    _points[p] = new List<GMap.NET.PointLatLng>();

                    foreach (COORDS coord in _list)
                    {                        
                        _points[p].Add(new GMap.NET.PointLatLng(coord.lat, coord.lon));
                    }
                                        
                    _route[p] = new GMapRoute(_points[p], TH1.P.BODY_TABLE[p].OS.name_0);
                    _route[p].Stroke.Color = TH1.P.BODY_TABLE[p].OS.color;
                    _route[p].Stroke.Brush = new SolidBrush(TH1.P.BODY_TABLE[p].OS.color);
                    _route[p].Stroke.Width = (int)numericUpDownPen.Value;
                    _overlay[p] = new GMapOverlay(p.ToString());
                    _overlay[p].Routes.Add(_route[p]);                          
                    gMapControl1.Overlays.Add(_overlay[p]);
                    gMapControl1.UpdateRouteLocalPosition(_route[p]);                    
                }

**Comment by jhofran** [comment]
error = _route[p].Stroke.Color = TH1.P.BODY_TABLE[p].OS.color;

ok = routes.Stroke = new Pen(Color.FromArgb(144, Color.FromArgb(rnd.Next(256), rnd.Next(256), rnd.Next(256))));

**Comment by sebsebien** [comment]
@jhofran, Thanks a lot for the information. It's working fine now.
