### ISSUE TITLE
Here maps error

### ISSUE THREAD

**Issue by Stephanowicz** [judero01col/GMap.NET#11]
Hi,

I was glad to see that there's still work in progress on this great project!
Nevertheless, **here** maps returns an error **400 Bad Request** 
The string e.g is 
`Address = {http://4.traffic.maps.cit.api.here.com/maptile/2.1/traffictile/newest/normal.day/16/34979/22632/256/png8?app_id=&app_code=}`

Any ideas?

Cheers,

Stephan

**Comment by Stephanowicz** [comment]
O.k. - got it!
Access to here maps api only with **AppId** and **AppCode** ...
That's annoying ;)

Cheers,

Stephan

**Comment by judero01col** [comment]
Hello, sorry for the delay in answering, I was traveling. Effectively to access a Here Map, it is necessary AppId and AppCode, without this you can not user.

Greetings.
