### ISSUE TITLE
YourNavigation.org - is it down?

### ISSUE THREAD

**Issue by devsoft-express** [judero01col/GMap.NET#118]
Hello ppl,
is the provider for the OS down ? 
YourNavigation.org seems to be down since this morning and i cannot find the reasons. 
Anyone knows what`s happening?

Thanks

**Comment by zgabi** [comment]
Yes, it seems that it is down. You should ask them.

**Comment by Giggeler** [comment]
Is there an alternative to this provider with the same interface?

**Comment by devsoft-express** [comment]
I moved to Google Maps, didn t find another free service yet.

**Comment by devsoft-express** [comment]
At least not one that its reliable so it can be placed in production environments

**Comment by zgabi** [comment]
I close it, since this is not a GMap.NET issue.
