### ISSUE TITLE
GoogleMapProvider.Instance.GetRoute on all Providers always return null

### ISSUE THREAD

**Issue by jalalipm** [judero01col/GMap.NET#128]
when I use the GoogleMapProvider.Instance.GetRoute  (for example provide is OpenCycleMap) function I get always null.
I have tested different providers and the same issue.

the component version that I use :
GMap.NET.Core => 1.7.5.0
GMap.NET.WindowsForms => 1.7.5.0

**Comment by cassieve** [comment]
Try using this...

Set google api key
GMapProviders.GoogleMap.ApiKey = "Your key";
Then use 
GDirections myDirections;
var rt = GMapProviders.GoogleMap.GetDirections(out myDirections, FromLocation,WaypointsList, LastLocation, false, false, false, false, false);
var route = new GMapRoute(myDirections.Route, "route");
OverlayRoutes.Routes.Add( new GMapRoute( route.Points,"tst"));
