### ISSUE TITLE
REQUEST DENIED in getDirections()

### ISSUE THREAD

**Issue by Speirs47** [judero01col/GMap.NET#13]
Here's my VB.Net code:
> Dim gd As New GDirections
> GMapProviders.GoogleMap.ApiKey = "MY API KEY"
> Dim xx As GMap.NET.DirectionsStatusCode = GMapProviders.GoogleMap.GetDirections(gd, startRoute.Position, endRoute.Position, False, False, False, False, True)

And the last line returns REQUEST_DENIED code (6). I'm 100% sure that api key is correct as I have no problem using it in Firefox.

**Comment by Speirs47** [comment]
It seems to me that GMap is accessing API with HTTPS instead of HTTPS and that's the problem

**Comment by judero01col** [comment]
Greetings, you are correct the error must be used in the place of https and in the correction and sending of the changes in the repository in the hours is also published in the Nuget. Thanks for the report.

**Comment by judero01col** [comment]
publish a new version with this correction, could you tell me if your problem is solved.

      MainMap.MapProvider = GMapProviders.GoogleMap;
      GDirections gd = null;
      DirectionsStatusCode Res = MainMap.DirectionsProvider.GetDirections(out gd, MainMap.Position, new PointLatLng(54.7261334816182, 25.2985095977783), false, false, false, false, true);

      if (Res == DirectionsStatusCode.OK)
      {
             //Code Here
      }

**Comment by santoniFlor** [comment]
Hi! Im having the same issue when i try to get the routes. Also i tried what u posted judero01col but i can fix it. Can u please help me ?? Thanks !

**Comment by umair1222** [comment]
> publish a new version with this correction, could you tell me if your problem is solved.
> 
> ```
>   MainMap.MapProvider = GMapProviders.GoogleMap;
>   GDirections gd = null;
>   DirectionsStatusCode Res = MainMap.DirectionsProvider.GetDirections(out gd, MainMap.Position, new PointLatLng(54.7261334816182, 25.2985095977783), false, false, false, false, true);
> 
>   if (Res == DirectionsStatusCode.OK)
>   {
>          //Code Here
>   }
> ```

i use this code but status has Requst_Denied how i can fix this if u find solution contact me on
umairkhan269@gmail.com

**Comment by Robert969696** [comment]
I got same issue, any solution to this?

**Comment by dcsnetlink** [comment]
Has this been resolved?  I am using 2.1.7.0 and  get this error when I attempt to get a route.
I have enabled the correct APIs and left it unrestricted.

**Comment by neojudgment** [comment]
> Has this been resolved? I am using 2.1.7.0 and get this error when I attempt to get a route. I have enabled the correct APIs and left it unrestricted.

Apparently it's not solved ! Same problem here in WPF.

**Comment by Yogesh12326** [comment]
Is it resolved now ?
