### ISSUE TITLE
[2.0.2] OpenStreetMap: the remote server returned an error 418 blocked

### ISSUE THREAD

**Issue by xavierdono** [judero01col/GMap.NET#137]
Hi, I upgraded from 2.0.1 to 2.0.2 and I got this error 418 blocked.

Initialization of the map:

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;

 GMapProvider.WebProxy = System.Net.WebRequest.GetSystemWebProxy();
GMapProvider.WebProxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;

 this.MainMap.MapProvider = GMapProviders.OpenStreetMap;
this.MainMap.ShowCenter = false;
this.MainMap.MinZoom = 2;
this.MainMap.MaxZoom = 18;
this.MainMap.Zoom = 15;
this.MainMap.DragButton = System.Windows.Forms.MouseButtons.Left;
this.MainMap.Manager.Mode = AccessMode.ServerOnly;
this.MainMap.MouseWheelZoomType = MouseWheelZoomType.MousePositionWithoutCenter;
this.MainMap.PolygonsEnabled = false;
this.MainMap.RoutesEnabled = false;
this.MainMap.ScaleMode = ScaleModes.Fractional;`

Any ideas?

BR,
Xavier

**Comment by OgreTransporter** [comment]
I can confirm that. OpenStreetMap, OpenSeaMapHybrid and all MapQuest sources do not work.

**Comment by felixZmn** [comment]
can confirm that too.

OpenCycleMapProvider, OpenCycleTransportMapProvider, OpenCycleLandscapeMapProvider and OpenStreet4UMapProvider do work perfectly fine.

**Comment by judero01col** [comment]
please test if version 2.1.5 fixes your problem

**Comment by OgreTransporter** [comment]
Works with 2.1.6
