### ISSUE TITLE
Changes to ObservableCollection.cs

### ISSUE THREAD

**Issue by revolutio-au** [judero01col/GMap.NET#149]
Hi,

I notice there has been some breaking changes compared with v1.9.3 for GMap.NET.WindowsForms/GMap.Net/ObjectModel/ObservableCollection.cs.

v1.9.3 supported functionality for inserting and removing polygons to Overlays, but the new version does not appear to. When I replace the current ObservableCollection.cs file with that from v1.9.3, the functionality is restored and the errors I was getting in v2.0.2 and v2.0.3 with code that worked in v1.9.3 (a couple below) no longer occur. Are any contributors able to clarify why these changes were made?

Example 1: Inserting Polygon Overlay (works in v1.9.3)

Overlays.Shielding.Polygons.Insert(0, Map.Draw.Sector.Border(w, InfluenceDistance, 0, Core.Directions.Eight.Name(w) & " Wind Shielding Zone", New Pen(Color.White, 2)))

Example 2: Removing Existing Polygons (works in v1.9.3)

For Each Polygon As WindowsForms.GMapPolygon In Building.Polygons
        Overlays.Footprints.Polygons.Remove(Overlays.Footprints.Polygons.FirstOrDefault(Function(k) k Is Polygon))
Next

**Comment by fabrizioPucci** [comment]
I think that I have the same problem from 2.0.1 to 2.0.3. 
Now
     Overlay.Routes.IndexOf(route)
gives me an error

**Comment by revolutio-au** [comment]
Any thoughts please, @judero01col ?

**Comment by judero01col** [comment]
please test if version 2.1.4 fixes your problem. @revolutio-au @fabrizioPucci

**Comment by revolutio-au** [comment]
No, still no good I'm afraid. I get the this error when trying to access the polygon using the following code: "'Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index'"

`For Each Polygon As WindowsForms.GMapPolygon In Building.Polygons
       Overlays.Footprints.Polygons.Remove(Overlays.Footprints.Polygons.FirstOrDefault(Function(k) k Is Polygon))
Next`

However, if I replace ObservableCollection.cs and ObservableCollectionThreadSafe.cs in v2.1.4 with the code from v1.9.3, it works just fine.

I also note that the "Insert" method has been removed when comparing with v1.9.3.

**Comment by judero01col** [comment]
Insert and IndexOf are implemented in ObservableCollection. please test if version 2.1.5 fixes your problem

**Comment by revolutio-au** [comment]
Thank you Jurgen, that did the trick. I appreciate all the effort you've put in to keep this code up to date! :)
