### ISSUE TITLE
NuGet Package Dependency

### ISSUE THREAD

**Issue by Chadley08** [judero01col/GMap.NET#15]
When I use nuget to install GMap.NET into my solution, and if I am using the GoogleMapsProvider, after I deploy/install my application, when I attempt to make a call to the Maps elevation API, or when I am trying to make a call to the Javascript Maps API, I get an exception.

"Could not load file or dependency Newtsonsoft.Json v9.0.0"...

The nuget package I download says that the library is compatible with Newtonsoft.Json >= 9.0.1 for v1.8.5. However, the library is looking for v9.0.0. I think the dependency needs to be updated in your nuspec file.

I also downloaded the source from github and compiled the libraries, then manually included them in my project after uninstalling GMap through nuget, but keeping the required depedencies. The version mismatch error went away.

**Comment by judero01col** [comment]
thank you very much for the information, I will include this correction version 1.8.6 and try to publish tomorrow afternoon, greetings.

**Comment by ARA-Trans** [comment]
Hello,

I will check the new version and get back to you.

**Comment by Chadley08** [comment]
Hello,

I will update to the new version, confirm the fix, and get back to you.
