### ISSUE TITLE
open street maps problem

### ISSUE THREAD

**Issue by pahahi** [judero01col/GMap.NET#16]
Hello.

I have a problem with a function GetRoute that does not affect the value of Duration (it is always null, distance is ok) version 1.8.5

best regards

**Comment by judero01col** [comment]
I already found the error, the solution I am going to publish in version 1.8.6, I will try to publish tomorrow afternoon, greetings

**Comment by judero01col** [comment]
publish a new version with this correction, could you tell me if your problem is solved.

MainMap.MapProvider = GMapProviders.OpenStreetMap;
MapRoute Route = MainMap.RoutingProvider.GetRoute(MainMap.Position, new PointLatLng(54.7261334816182, 25.2985095977783), false, false, 10);

                if (Route != null && Route.Status == RouteStatusCode.OK)
                {
                    GMapRoute oRoute = new GMapRoute(Route.Points, "Route");
                    routes.Routes.Add(oRoute);
                }
