### ISSUE TITLE
gmap don't work with local OSM

### ISSUE THREAD

**Issue by termidoyarka** [judero01col/GMap.NET#20]

**Comment by termidoyarka** [comment]
I have local OSM tile server. Address http://localhost/osm_tiles/{x}/{y}/{z}.png How use GMAP for with case?

**Comment by judero01col** [comment]
greetings, at this time gmap, does not implement local OSM, if you can provide me with a public url to perform tests, I could very much make such an implementation.

**Comment by judero01col** [comment]
Greetings, in version 1.9.1 of the custom provider, to use the library with other map providers.

         // Custom Map Provider
         MainMap.MapProvider = GMapProviders.CustomMap;
         GMapProviders.CustomMap.CustomServerUrl = "http://{l}.localhost/osm_tiles/{x}/{y}/{z}.png";
         GMapProviders.CustomMap.CustomServerLetters = "abc";

if you do not use server letter, you should not specify it and the url should not contain {i}

Please let me know if your implementation worked with this provider.

**Comment by GusGiann** [comment]
Is it possible to Know what local OSM tile server you use ?
Because I am Really interrested in that kind of solution.!!
Thank you !

**Comment by judero01col** [comment]
Sorry, I do not understand your question. You can apply a little more.

**Comment by GusGiann** [comment]
Question about Local Map Server is for user **termidoyarka**

**Comment by GusGiann** [comment]
> 
> 
> I have local OSM tile server. Address [http://localhost/osm_tiles/{x}/{y}/{z}.png](http://localhost/osm_tiles/%7Bx%7D/%7By%7D/%7Bz%7D.png) How use GMAP for with case?

Is it possible to Know what local OSM tile server you use ?
Because I am Really interrested in that kind of solution.!!
Thank you !

**Comment by judero01col** [comment]
ok, sorry I did not realize

**Comment by termidoyarka** [comment]
> Приветствия, в версии 1.9.1 пользовательского поставщика, для использования библиотеки с другими поставщиками карт.
> 
> ```
>   // Custom Map Provider
>   MainMap.MapProvider = GMapProviders.CustomMap;
>   GMapProviders.CustomMap.CustomServerUrl = "http://{l}.localhost/osm_tiles/{x}/{y}/{z}.png";
>   GMapProviders.CustomMap.CustomServerLetters = "abc";
> ```
> если Вы не используете серверную букву, Вы не должны указывать ее и url не должен содержать {I}
> 
> Пожалуйста, дайте мне знать, если ваша реализация работала с этим поставщиком.

Thanks!
