### ISSUE TITLE
GetDirections() throws json exception

### ISSUE THREAD

**Issue by AltoControl** [judero01col/GMap.NET#22]
I dont understand what am i doing wrong to be honest, GetDirections() is throwing a 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
tried to upgrade my json version but that didnt do the trick

**Comment by judero01col** [comment]
Greetings, perform the test with the library method using Google Map Map Provider and OpenStreetMap and work without problems. It could indicate how you were using it and what provider, if you are using the sources or the nuget and if you are using an apikey. I leave an example as I am using it.


GeoCoderStatusCode status = MainMap.SetPositionByKeywords(textBoxGeo.Text);
if (status != GeoCoderStatusCode.G_GEO_SUCCESS)
{
       MessageBox.Show("Geocoder can't find: '" + textBoxGeo.Text + "', reason: " + status.ToString(), "GMap.NET", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
}

**Comment by AltoControl** [comment]
Im using the nuget package, an api key and the google providers, actually the SetPositionByKeywords and GetPoint methods works fine. The problem is with the GetDirections that throws me an exceptionincode {8}, the debuggers tells me its a JsonReaderException, GetRoute doesnt work neither. I leave an example of the code:

Dim Start as New PointLatLng(Latitud, Longitud)
Dim End as New PointLatLng(Latitud2, Longitud2)

Dim Direction as  GDirections
Dim Status As DirectionsStatusCode = DirectionsStatusCode.NOT_FOUND
Status = GMap.NET.MapProviders.GoogleMapProvider.Instance.GetDirections(Direction , Start , End , False, False, False, False, True) ---Boom

Same problem if i use String instead of PointLatLng

GetRoute doesnt throw me an exception but the list of points it returns is empty

**Comment by judero01col** [comment]
publish a new version with this correction, could you tell me if your problem is solved.

**Comment by AltoControl** [comment]
GetDirections(GDirections, PointLatLng, PointLatLng, Boolean, Boolean, Boolean, Boolean) is working fine now (Thank you very much!!!)

GetDirections(GDirections, String, String, Boolean, Boolean, Boolean, Boolean, Boolean) is still throwing an exceptionincode {8}

**Comment by judero01col** [comment]
Thank you very much for the warning, the correction was made, update to version 1.8.8

**Comment by AltoControl** [comment]
Update it, but im getting a Unable to load DLL 'SQLite.Interop.DLL', i tried to uninstall it and install it again with all the dependencies, but no luck

**Comment by judero01col** [comment]
These are the libraries and the versions that you should have installed, please check and confirm.

![image](https://user-images.githubusercontent.com/22176530/47937265-2880b700-deae-11e8-8546-c02ab53e302d.png)

**Comment by AltoControl** [comment]
checked and confirmed, i could downgrade to 1.8.7 and it was the same problem, i could compile with 1.8.6

**Comment by AltoControl** [comment]
This is what i did and the results:

*Started a new proyect, download and installed the nuget package -- No problem there.
*New WPF window with a WPF gmap control -- Unable to load DLL 'SQLite.Interop.DLL'
*New Forms window with a Forms gmap control - No problem there.
*New WPF window with a Forms gmap control -- Unable to load DLL 'SQLite.Interop.DLL'

**Comment by AltoControl** [comment]
Found out the problem, our project use Net Framework 4.0 which is the max in windows xp and sqlite 1.0.109.2 needs 4.5, so we will probably stay in 1.8.6. 
Thanks for you patience and hard work, cheers

**Comment by judero01col** [comment]
Greetings, thanks for your report, I made some changes in the project to be compatible with the framework 4.0, please try and tell me.

**Comment by AltoControl** [comment]
1.9 work great in both GetDirection, so i will close this issue.
Again, thanks for your hard work
