### ISSUE TITLE
How to dynamically change GMapMarker content using Timer?

### ISSUE THREAD

**Issue by digibum** [judero01col/GMap.NET#4]
I have a custom GMapMarker class that draws a simple image to map... How to make that image to change its properties (lets say blink) in interval of 500ms?

I could call GMapControl.Invalidate() from Timer. This will cause my entire map to redraw, which is not desirable. I only need my custom GMapMarker to redraw.

Is there any better solution for this? How about using internal Timer and call Redraw from marker itself? Is this possible?

**Comment by judero01col** [comment]
Greetings, I already solve your problem or even require help ??
