### ISSUE TITLE
getroute always return null

### ISSUE THREAD

**Issue by fvilanova** [judero01col/GMap.NET#47]
I am using the component for a few months and was working perfect... But now when I use the  GMapProviders.OpenStreetMap.GetRoute function I get always null.

I have tested different providers and the same issue.

**Comment by judero01col** [comment]
Please check if the problem persists in version 1.9.3. and leave your comment.

**Comment by fvilanova** [comment]
Problem solved, with 1.9.3 version is working again

Thanks
