### ISSUE TITLE
in WPF, The Position dont work with double.Parse()

### ISSUE THREAD

**Issue by selticq** [judero01col/GMap.NET#55]
Problems while trying to pass double.Parse() values to Position property of the map component.
this works:
Window.Map.Position = new GMap.NET.PointLatLng(50.555, 4.999);
but this not:
Window.Map.Position = new GMap.NET.PointLatLng(double.Parse("50.555"), double.Parse("4.999"));
I have an old sqlite database where longitude and latitude are stored as string, so i'm a little disappointed. Is there a solution?

**Comment by alexkhvlg** [comment]
https://stackoverflow.com/questions/5109816/double-parse-with-culture-format

**Comment by selticq** [comment]
Ok, it works. Thank you.

**Comment by selticq** [comment]
Résolve.

**Comment by selticq** [comment]
It works now . Thank you.
