### ISSUE TITLE
Can't integrate map control with Data Binding

### ISSUE THREAD

**Issue by SalehGladius** [judero01col/GMap.NET#6]
Xaml Code:
`<map:Map x:Name="MainMap" Position="{Binding Position}" Zoom="{Binding Zoom}" />`

Error:

![image](https://user-images.githubusercontent.com/8124646/36978214-f87c3116-2098-11e8-8705-de3a67d2973b.png)

**Comment by judero01col** [comment]
Greetings, in version 1.8.5 this feature is already included
