### ISSUE TITLE
What happened to ovi maps ?

### ISSUE THREAD

**Issue by luisarvayo** [judero01col/GMap.NET#7]
Ovi maps is no longer working. 
Inside source code you will find

RefererUrl = "http://maps.ovi.com/";

But that url is no longer working. Please help.

**Comment by judero01col** [comment]
Cordial Regards,

OviMaps is no longer available, you must use HereMap instead, the new version of GMap.NET.Windows 1.8.1 already includes HereMapProvider.

You must have an AppId and AppCode, you can use the tools to carry out your tests.

HereMapProvider.Instance.AppId = "7zifAuqOid6csXxmu24I";
HereMapProvider.Instance.AppCode = "f2ezLQ6bX8lK2EahPXsY6w";

I hope it helps.
