### ISSUE TITLE
Removing PocketPC support

### ISSUE THREAD

**Issue by zgabi** [judero01col/GMap.NET#71]
There are a lot of conditional compilations for PocketPC.
PocketPC was last supported in VS2008, and there is no PocketPC build of GMap.NET.

I'd like to remove that old codes. What do you think?

**Comment by judero01col** [comment]
Yes of course, I was thinking of doing the same.

**Comment by judero01col** [comment]
Please create a new branch and then merge it

**Comment by zgabi** [comment]
I'm a little bit busy now at work, but I'll do it.
