### ISSUE TITLE
SetPositionByKeywords

### ISSUE THREAD

**Issue by xvfaithvx** [judero01col/GMap.NET#72]
I have been unable to get this feature of the app to function and was hoping for some input on what I might be doing wrong. No matter what provider I've tried I end up with a map zoomed in to Lat/Lng 0,0. Thank you in advance for your assistance!

  gmap.MapProvider = GMap.NET.MapProviders.GMapProviders.BingMap;
            gmap.SetPositionByKeywords("Madrid, Spain");
            gmap.MinZoom = 0;
            gmap.MaxZoom = 24;
            gmap.Zoom = 13;
            gmap.AutoScroll = true;
            GMap.NET.GMaps.Instance.Mode = GMap.NET.AccessMode.ServerAndCache;

**Comment by zgabi** [comment]
Please try to set the API key and try it with google maps provider:
GoogleMapProvider.Instance.ApiKey = "xxxx";

You can register for this api key for free. (Of course it has limitation comparing to the paid versions)
I tried it some weeks ago, and worked.

**Comment by xvfaithvx** [comment]
Thanks for the suggestion! I also realized that I was working with an older version of the package and once I updated to the new version I have been successful with the SetPositionByKeywords when using the ArcGIS provider.
