### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by xlnd47** [judero01col/GMap.NET#75]
The problem I have with routes is, the route itself is showing in flight distances. 
To make this look better I made an extra API call to google maps for directs and add every point of the directions to the route. But now its showing flight distances between the different direction points.

![image](https://user-images.githubusercontent.com/26673889/73843240-8b35d080-481e-11ea-8a64-f11543b63770.png)

Like you can see in my image. 

Does anybody know a solution for this? I added a legit/working API key to it.

**Comment by HungLearner** [comment]
Hi, this problem is "Route" parameter only provides a part of the points.
If you want to get all points, get each step array.
` for (int i = 0; i < _GDirections.Steps.Count; i++)
  {
        for (int j = 0; j < _GDirections.Steps[i].Points.Count; j++)
             _GDirections.Route.Add(_GDirections.Steps[i].Points[j]);
  }`

**Comment by HungLearner** [comment]
> The problem I have with routes is, the route itself is showing in flight distances.
> To make this look better I made an extra API call to google maps for directs and add every point of the directions to the route. But now its showing flight distances between the different direction points.
> 
> ![image](https://user-images.githubusercontent.com/26673889/73843240-8b35d080-481e-11ea-8a64-f11543b63770.png)
> 
> Like you can see in my image.
> 
> Does anybody know a solution for this? I added a legit/working API key to it.

Hi, this problem is "Route" parameter only provides a part of the points.
If you want to get all points, get each step array.

```
for (int i = 0; i < _GDirections.Steps.Count; i++)
{ 
  for (int j = 0; j < _GDirections.Steps[i].Points.Count; j++) 
  _GDirections.Route.Add(_GDirections.Steps[i].Points[j]);
}
```
