### ISSUE TITLE
Lantmäteriet SWEREF99 improvements: Mercator Projection

### ISSUE THREAD

**Issue by jokubokla** [judero01col/GMap.NET#79]
Hello all,
this git repo was a BIG HELP for me since I'm searching for quite some time how to get the famous "Lantmäteriet" map from Sweden offline on my Android device. Today I experienced the breakthrough:

1) I would be able to provide the correct Projection Information for the leaflet output of this project if one is using the Lantmäteriet map in EPSG:3006. The given "gmap-lt.html" does not seem to work properly.

2) Further more, by playing with QGIS and Lantmäteriet WMTS "GetCapabilities" I found out that there is an alternative Lantmäteriet projection EPSG:3857 which is Mercator (and therefore compatible with LOCUS Maps or Orux Maps since both can't use EPSG:3006 as far as I understand). In case one uses GMap.Net to create an offline Maptiles Database (like I do) this helps tremendously. So I wrote a GMapProvider for Sweden in Mercator which presumably could be of some help for some of you.

My problem is that I'm not at all familiar with git and I don't have a clue how to "contribute" or "fork" or something else.

So if one is interested in the two topics described above please let me know. I'm willing to share my code to improve this project.

Thanks
Jörg

**Comment by zgabi** [comment]
Hi,

1) I can help you with git. (fork, commit, push) It is not so hard.

Or if you don't want to learn it, just:
2) Download the latest code, make the modifications, ZIP it, and send it to me.. I'll check and commit your changes.

**Comment by jokubokla** [comment]
Hi Zavarkó,
let me fool around a bit with fork, commit and push. If I'm not successful I will get back to you.
Thanks
Jörg

**Comment by jokubokla** [comment]
Hi all,
**I screwed up quite a bit.** The project I used and improved was not this one (_judero01col/GMap.NET_) but another (_radioman/greatmaps_).

So when I started this conversation yesterday I started it in the wrong spot. Actually I added the new Projection (using the git stuff) to the other project. I would love to do the same here but I'm not able to compile this project in my development environment at all (VS Community 2017). 

Thanks
Jörg

**Comment by zgabi** [comment]
Hi,

Yes, it needs VS 2019. (Community is probably ok, but I haven't tried it.

**Comment by jokubokla** [comment]
Hi,
I updated to VS2019 and was able to compile. Community is sufficient. I also learned a bit about git and my "fork" is now a "pull request".

Thanks for your support. 
Jörg

**Comment by jokubokla** [comment]
Hi Zavarkó,
now I'm addicted :-) Here is what I have in mind: The Windows Forms Demo is somewhat "ugly", especially for newbies. The Office2007 style panel really seems outdated and some functions, like Flight Radar demo don't even work properly anymore. I can't even open the form in desing mode without getting errors. Can you?

IMHO, a Demo should be more "lightweight" and easy to understand for newbies. I have a lot of ideas how to clean it out and how to build a demo which is easier to use and easier to understand. I would volounteer to do that, but if I make these changes and they don't find their way back into the master it would be a waste of time.

What do you think? Is there a whishlist for "Windows Form Demo improvements" on your side? Do you think it would be worth to invest some time?

Please let me know what you think about this idea.

Thanks
Jörg

**Comment by zgabi** [comment]
I also can't open the Winforms designer.

I like your idea.
But the owner of the project is @judero01col , so he should agree. 

If you check the commit history, you can see that my first commit was in nov 2019, so I was the same contributor as you:)

We are using WPF in our project, so if you can maintain the WinForms part, that would be great. I also plan to make improvements in this project, because we have some problem in a .NET Core project, but currently we have a lot of other higher priority issues :(

**Comment by judero01col** [comment]
hello everyone, any contribution is welcome, you will have no problem comparing those changes to the master

**Comment by zgabi** [comment]
I close this issue, feel free to create new PRs and/or issues.

**Comment by jokubokla** [comment]
will do
