### ISSUE TITLE
OpenStreetMapProvider doesn't set recommended header - `X-Yours-client` 

### ISSUE THREAD

**Issue by shrayasr** [judero01col/GMap.NET#84]
The [documentation](https://wiki.openstreetmap.org/wiki/YOURS#Version_1.0) on yournavigation - the API used in `OpenStreetMapProvider` recommends to set a `X-Yours-Client` header to help tracking and to allow the developer to get in touch in case an application is overloading the service. 

From the documentation on Usage (Emphasis mine): 

> Use of the API is on a Fair Use Policy basis: everyone can use the API as long as it won't overload the server systematically. If you do overload but provide an X-Yours-client header (as described below) then I'll try to contact you to find a solution. **If you don't provide this information (or I can't contact you) then you might become blocked** (this has happened only once so far, so don't worry too much about it).

The right thing to do might be to allow anyone using the provider to set this header if they see fit.

Open to your thoughts? Happy to also work on a PR for this if you're OK with accepting this change.

**Comment by zgabi** [comment]
Ok, please create a PR.

If I understood correctly it should be set by the user of the GMap.NET, it should not be the same for all Gmap.NET users, right? As the Api key.

**Comment by shrayasr** [comment]
Correct, yes.

**Comment by shrayasr** [comment]
@zgabi How would you propose we go about this? All requests seem to be going through `GMapProviders.GetContentUsingHttp`. But this only takes a `url`. How do you propose we send the extra piece of information only in the case of `OpenStreetMapProvider`?

**Comment by zgabi** [comment]
I propose to add a new virtual method to the GMapProvider class, like:
protected virtual void InitializeWebRequest(WebRequest request)
{
}

And override it in OSM provider.

Besides the `GetContentUsingHttp `there is a second method which is creating a http request: `GetTileImageUsingHttp`.

**Comment by shrayasr** [comment]
Yes, that makes sense. How do we handle if the request is a `SocksHttpWebRequest`? I've not worked with that before.

**Comment by shrayasr** [comment]
Oh wait, either way it is a `WebRequest`. That would work.

**Comment by shrayasr** [comment]
@zgabi I see a property called `Name` under `OpenStreetMapProvider`. Should I just send that to `X-Yours-client` or do you think it makes sense to define another `YoursClientName` property?

**Comment by zgabi** [comment]
Since that property is readonly, I don't think that it would be a good idea to use the Name property.
The users are not allowed to modify it, so if you use the Name, all the GMap.NET users will send the "OpenStreetMap" string.

**Comment by zgabi** [comment]
So I think you need to add a new property, which is null by default, and send it only when the user sets it.

**Comment by shrayasr** [comment]
Done, @zgabi, please check at your leisure :)
